# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/cmake/283/bin/cmake

# The command to remove a file.
RM = /snap/cmake/283/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/harald/source/repos/magnificence-chess

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/harald/source/repos/magnificence-chess

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/cmake/283/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/snap/cmake/283/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/harald/source/repos/magnificence-chess/CMakeFiles /home/harald/source/repos/magnificence-chess/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/harald/source/repos/magnificence-chess/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named magnificence-chess

# Build rule for target.
magnificence-chess: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 magnificence-chess
.PHONY : magnificence-chess

# fast build rule for target.
magnificence-chess/fast:
	$(MAKE) -f CMakeFiles/magnificence-chess.dir/build.make CMakeFiles/magnificence-chess.dir/build
.PHONY : magnificence-chess/fast

src/ABAI.o: src/ABAI.cpp.o

.PHONY : src/ABAI.o

# target to build an object file
src/ABAI.cpp.o:
	$(MAKE) -f CMakeFiles/magnificence-chess.dir/build.make CMakeFiles/magnificence-chess.dir/src/ABAI.cpp.o
.PHONY : src/ABAI.cpp.o

src/ABAI.i: src/ABAI.cpp.i

.PHONY : src/ABAI.i

# target to preprocess a source file
src/ABAI.cpp.i:
	$(MAKE) -f CMakeFiles/magnificence-chess.dir/build.make CMakeFiles/magnificence-chess.dir/src/ABAI.cpp.i
.PHONY : src/ABAI.cpp.i

src/ABAI.s: src/ABAI.cpp.s

.PHONY : src/ABAI.s

# target to generate assembly for a file
src/ABAI.cpp.s:
	$(MAKE) -f CMakeFiles/magnificence-chess.dir/build.make CMakeFiles/magnificence-chess.dir/src/ABAI.cpp.s
.PHONY : src/ABAI.cpp.s

src/BitBoard.o: src/BitBoard.cpp.o

.PHONY : src/BitBoard.o

# target to build an object file
src/BitBoard.cpp.o:
	$(MAKE) -f CMakeFiles/magnificence-chess.dir/build.make CMakeFiles/magnificence-chess.dir/src/BitBoard.cpp.o
.PHONY : src/BitBoard.cpp.o

src/BitBoard.i: src/BitBoard.cpp.i

.PHONY : src/BitBoard.i

# target to preprocess a source file
src/BitBoard.cpp.i:
	$(MAKE) -f CMakeFiles/magnificence-chess.dir/build.make CMakeFiles/magnificence-chess.dir/src/BitBoard.cpp.i
.PHONY : src/BitBoard.cpp.i

src/BitBoard.s: src/BitBoard.cpp.s

.PHONY : src/BitBoard.s

# target to generate assembly for a file
src/BitBoard.cpp.s:
	$(MAKE) -f CMakeFiles/magnificence-chess.dir/build.make CMakeFiles/magnificence-chess.dir/src/BitBoard.cpp.s
.PHONY : src/BitBoard.cpp.s

src/Board.o: src/Board.cpp.o

.PHONY : src/Board.o

# target to build an object file
src/Board.cpp.o:
	$(MAKE) -f CMakeFiles/magnificence-chess.dir/build.make CMakeFiles/magnificence-chess.dir/src/Board.cpp.o
.PHONY : src/Board.cpp.o

src/Board.i: src/Board.cpp.i

.PHONY : src/Board.i

# target to preprocess a source file
src/Board.cpp.i:
	$(MAKE) -f CMakeFiles/magnificence-chess.dir/build.make CMakeFiles/magnificence-chess.dir/src/Board.cpp.i
.PHONY : src/Board.cpp.i

src/Board.s: src/Board.cpp.s

.PHONY : src/Board.s

# target to generate assembly for a file
src/Board.cpp.s:
	$(MAKE) -f CMakeFiles/magnificence-chess.dir/build.make CMakeFiles/magnificence-chess.dir/src/Board.cpp.s
.PHONY : src/Board.cpp.s

src/Engine.o: src/Engine.cpp.o

.PHONY : src/Engine.o

# target to build an object file
src/Engine.cpp.o:
	$(MAKE) -f CMakeFiles/magnificence-chess.dir/build.make CMakeFiles/magnificence-chess.dir/src/Engine.cpp.o
.PHONY : src/Engine.cpp.o

src/Engine.i: src/Engine.cpp.i

.PHONY : src/Engine.i

# target to preprocess a source file
src/Engine.cpp.i:
	$(MAKE) -f CMakeFiles/magnificence-chess.dir/build.make CMakeFiles/magnificence-chess.dir/src/Engine.cpp.i
.PHONY : src/Engine.cpp.i

src/Engine.s: src/Engine.cpp.s

.PHONY : src/Engine.s

# target to generate assembly for a file
src/Engine.cpp.s:
	$(MAKE) -f CMakeFiles/magnificence-chess.dir/build.make CMakeFiles/magnificence-chess.dir/src/Engine.cpp.s
.PHONY : src/Engine.cpp.s

src/GameState.o: src/GameState.cpp.o

.PHONY : src/GameState.o

# target to build an object file
src/GameState.cpp.o:
	$(MAKE) -f CMakeFiles/magnificence-chess.dir/build.make CMakeFiles/magnificence-chess.dir/src/GameState.cpp.o
.PHONY : src/GameState.cpp.o

src/GameState.i: src/GameState.cpp.i

.PHONY : src/GameState.i

# target to preprocess a source file
src/GameState.cpp.i:
	$(MAKE) -f CMakeFiles/magnificence-chess.dir/build.make CMakeFiles/magnificence-chess.dir/src/GameState.cpp.i
.PHONY : src/GameState.cpp.i

src/GameState.s: src/GameState.cpp.s

.PHONY : src/GameState.s

# target to generate assembly for a file
src/GameState.cpp.s:
	$(MAKE) -f CMakeFiles/magnificence-chess.dir/build.make CMakeFiles/magnificence-chess.dir/src/GameState.cpp.s
.PHONY : src/GameState.cpp.s

src/IO.o: src/IO.cpp.o

.PHONY : src/IO.o

# target to build an object file
src/IO.cpp.o:
	$(MAKE) -f CMakeFiles/magnificence-chess.dir/build.make CMakeFiles/magnificence-chess.dir/src/IO.cpp.o
.PHONY : src/IO.cpp.o

src/IO.i: src/IO.cpp.i

.PHONY : src/IO.i

# target to preprocess a source file
src/IO.cpp.i:
	$(MAKE) -f CMakeFiles/magnificence-chess.dir/build.make CMakeFiles/magnificence-chess.dir/src/IO.cpp.i
.PHONY : src/IO.cpp.i

src/IO.s: src/IO.cpp.s

.PHONY : src/IO.s

# target to generate assembly for a file
src/IO.cpp.s:
	$(MAKE) -f CMakeFiles/magnificence-chess.dir/build.make CMakeFiles/magnificence-chess.dir/src/IO.cpp.s
.PHONY : src/IO.cpp.s

src/MCAI.o: src/MCAI.cpp.o

.PHONY : src/MCAI.o

# target to build an object file
src/MCAI.cpp.o:
	$(MAKE) -f CMakeFiles/magnificence-chess.dir/build.make CMakeFiles/magnificence-chess.dir/src/MCAI.cpp.o
.PHONY : src/MCAI.cpp.o

src/MCAI.i: src/MCAI.cpp.i

.PHONY : src/MCAI.i

# target to preprocess a source file
src/MCAI.cpp.i:
	$(MAKE) -f CMakeFiles/magnificence-chess.dir/build.make CMakeFiles/magnificence-chess.dir/src/MCAI.cpp.i
.PHONY : src/MCAI.cpp.i

src/MCAI.s: src/MCAI.cpp.s

.PHONY : src/MCAI.s

# target to generate assembly for a file
src/MCAI.cpp.s:
	$(MAKE) -f CMakeFiles/magnificence-chess.dir/build.make CMakeFiles/magnificence-chess.dir/src/MCAI.cpp.s
.PHONY : src/MCAI.cpp.s

src/Main.o: src/Main.cpp.o

.PHONY : src/Main.o

# target to build an object file
src/Main.cpp.o:
	$(MAKE) -f CMakeFiles/magnificence-chess.dir/build.make CMakeFiles/magnificence-chess.dir/src/Main.cpp.o
.PHONY : src/Main.cpp.o

src/Main.i: src/Main.cpp.i

.PHONY : src/Main.i

# target to preprocess a source file
src/Main.cpp.i:
	$(MAKE) -f CMakeFiles/magnificence-chess.dir/build.make CMakeFiles/magnificence-chess.dir/src/Main.cpp.i
.PHONY : src/Main.cpp.i

src/Main.s: src/Main.cpp.s

.PHONY : src/Main.s

# target to generate assembly for a file
src/Main.cpp.s:
	$(MAKE) -f CMakeFiles/magnificence-chess.dir/build.make CMakeFiles/magnificence-chess.dir/src/Main.cpp.s
.PHONY : src/Main.cpp.s

src/MonteCarloAI.o: src/MonteCarloAI.cpp.o

.PHONY : src/MonteCarloAI.o

# target to build an object file
src/MonteCarloAI.cpp.o:
	$(MAKE) -f CMakeFiles/magnificence-chess.dir/build.make CMakeFiles/magnificence-chess.dir/src/MonteCarloAI.cpp.o
.PHONY : src/MonteCarloAI.cpp.o

src/MonteCarloAI.i: src/MonteCarloAI.cpp.i

.PHONY : src/MonteCarloAI.i

# target to preprocess a source file
src/MonteCarloAI.cpp.i:
	$(MAKE) -f CMakeFiles/magnificence-chess.dir/build.make CMakeFiles/magnificence-chess.dir/src/MonteCarloAI.cpp.i
.PHONY : src/MonteCarloAI.cpp.i

src/MonteCarloAI.s: src/MonteCarloAI.cpp.s

.PHONY : src/MonteCarloAI.s

# target to generate assembly for a file
src/MonteCarloAI.cpp.s:
	$(MAKE) -f CMakeFiles/magnificence-chess.dir/build.make CMakeFiles/magnificence-chess.dir/src/MonteCarloAI.cpp.s
.PHONY : src/MonteCarloAI.cpp.s

src/Move.o: src/Move.cpp.o

.PHONY : src/Move.o

# target to build an object file
src/Move.cpp.o:
	$(MAKE) -f CMakeFiles/magnificence-chess.dir/build.make CMakeFiles/magnificence-chess.dir/src/Move.cpp.o
.PHONY : src/Move.cpp.o

src/Move.i: src/Move.cpp.i

.PHONY : src/Move.i

# target to preprocess a source file
src/Move.cpp.i:
	$(MAKE) -f CMakeFiles/magnificence-chess.dir/build.make CMakeFiles/magnificence-chess.dir/src/Move.cpp.i
.PHONY : src/Move.cpp.i

src/Move.s: src/Move.cpp.s

.PHONY : src/Move.s

# target to generate assembly for a file
src/Move.cpp.s:
	$(MAKE) -f CMakeFiles/magnificence-chess.dir/build.make CMakeFiles/magnificence-chess.dir/src/Move.cpp.s
.PHONY : src/Move.cpp.s

src/MoveLogic.o: src/MoveLogic.cpp.o

.PHONY : src/MoveLogic.o

# target to build an object file
src/MoveLogic.cpp.o:
	$(MAKE) -f CMakeFiles/magnificence-chess.dir/build.make CMakeFiles/magnificence-chess.dir/src/MoveLogic.cpp.o
.PHONY : src/MoveLogic.cpp.o

src/MoveLogic.i: src/MoveLogic.cpp.i

.PHONY : src/MoveLogic.i

# target to preprocess a source file
src/MoveLogic.cpp.i:
	$(MAKE) -f CMakeFiles/magnificence-chess.dir/build.make CMakeFiles/magnificence-chess.dir/src/MoveLogic.cpp.i
.PHONY : src/MoveLogic.cpp.i

src/MoveLogic.s: src/MoveLogic.cpp.s

.PHONY : src/MoveLogic.s

# target to generate assembly for a file
src/MoveLogic.cpp.s:
	$(MAKE) -f CMakeFiles/magnificence-chess.dir/build.make CMakeFiles/magnificence-chess.dir/src/MoveLogic.cpp.s
.PHONY : src/MoveLogic.cpp.s

src/Test.o: src/Test.cpp.o

.PHONY : src/Test.o

# target to build an object file
src/Test.cpp.o:
	$(MAKE) -f CMakeFiles/magnificence-chess.dir/build.make CMakeFiles/magnificence-chess.dir/src/Test.cpp.o
.PHONY : src/Test.cpp.o

src/Test.i: src/Test.cpp.i

.PHONY : src/Test.i

# target to preprocess a source file
src/Test.cpp.i:
	$(MAKE) -f CMakeFiles/magnificence-chess.dir/build.make CMakeFiles/magnificence-chess.dir/src/Test.cpp.i
.PHONY : src/Test.cpp.i

src/Test.s: src/Test.cpp.s

.PHONY : src/Test.s

# target to generate assembly for a file
src/Test.cpp.s:
	$(MAKE) -f CMakeFiles/magnificence-chess.dir/build.make CMakeFiles/magnificence-chess.dir/src/Test.cpp.s
.PHONY : src/Test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... magnificence-chess"
	@echo "... edit_cache"
	@echo "... src/ABAI.o"
	@echo "... src/ABAI.i"
	@echo "... src/ABAI.s"
	@echo "... src/BitBoard.o"
	@echo "... src/BitBoard.i"
	@echo "... src/BitBoard.s"
	@echo "... src/Board.o"
	@echo "... src/Board.i"
	@echo "... src/Board.s"
	@echo "... src/Engine.o"
	@echo "... src/Engine.i"
	@echo "... src/Engine.s"
	@echo "... src/GameState.o"
	@echo "... src/GameState.i"
	@echo "... src/GameState.s"
	@echo "... src/IO.o"
	@echo "... src/IO.i"
	@echo "... src/IO.s"
	@echo "... src/MCAI.o"
	@echo "... src/MCAI.i"
	@echo "... src/MCAI.s"
	@echo "... src/Main.o"
	@echo "... src/Main.i"
	@echo "... src/Main.s"
	@echo "... src/MonteCarloAI.o"
	@echo "... src/MonteCarloAI.i"
	@echo "... src/MonteCarloAI.s"
	@echo "... src/Move.o"
	@echo "... src/Move.i"
	@echo "... src/Move.s"
	@echo "... src/MoveLogic.o"
	@echo "... src/MoveLogic.i"
	@echo "... src/MoveLogic.s"
	@echo "... src/Test.o"
	@echo "... src/Test.i"
	@echo "... src/Test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

